### ISSUE TITLE
Permitir copiar os textos da ofensa e réplica

### ISSUE THREAD

**Issue by joaomaas** [wendeldavid/ffge#10]
Permitir que o texto dos balões de ofensa e réplica sejam copiados. Assim é possível acessar links disponíbilizados nos textos.

Se possível, quando a ofensa ou réplica for uma imagem, carregar a imagem no navegador.

**Comment by ftoresan** [comment]
Sugiro também bloquear endereços locais, suportando apenas HTTP, HTTPS ou FTP.

**Comment by wendeldavid** [comment]
Melhoria de usabilidade realizada.
